server:
  port: 8080

spring:
  application:
    name: spotify-lyrics-backend
  
  h2:
    console:
      enabled: true
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

# API Keys (will be set via environment variables)
openai:
  api-key: ${OPENAI_API_KEY:}

spotify:
  client-id: ${SPOTIFY_CLIENT_ID:}
  client-secret: ${SPOTIFY_CLIENT_SECRET:}
  redirect-uri: ${SPOTIFY_REDIRECT_URI:http://localhost:8080/login/oauth2/code/spotify}

logging:
  level:
    com.spotifylyrics: DEBUG
    org.springframework.security: DEBUG